# Generated by Django 4.2.7 on 2026-01-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('role', models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer'), ('delivery', 'Delivery Person')], max_length=15)),
            ],
        ),
    ]
